### ISSUE TITLE
Exception in thread "main" java.net.UnknownHostException: secure.lan

### ISSUE THREAD

**Issue by Ibrahimous** [maaaaz/misc_hookons_avec_javasnoop#1]
$ uname -a
Linux debian 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux

$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

$ java -jar SecureCommunications.jar 
Welcome to SecureCommunications
Enter your message then press ENTER
Goodbye, World !
Exception in thread "main" java.net.UnknownHostException: secure.lan
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625)
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
    at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
    at securecommunications.HttpRequest.sendGet(HttpRequest.java:80)
    at securecommunications.SecureCommunications.main(SecureCommunications.java:34)

**Comment by arnaudsoullie** [comment]
Bonjour,

_"Exception in thread "main" java.net.UnknownHostException: secure.lan"_ ==> votre machine ne sait pas résoudre le nom de domaine _secure.lan_, ce qui est normal.

Le code ne comprend que la partie client, pas la partie serveur. Ainsi, la requête ne peut aboutir.
L'idée est justement de placer des hooks pour intercepter la requête et la modifier sans avoir à comprendre l'intégralité des mécanismes cryptographiques utilisés.

Pour rendre le programme plus fonctionnel : 
- Créer une résolution locale pour _secure.lan_ en modifiant le fichier "/etc/hosts"
- Lancer un serveur Apache en écoute
- Utiliser le certificat founi dans ce repo
- Créer un fichier _index.php_ à la racine du serveur web qui répond "200 OK"
